[package]
name = "mcfl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.4"
pest_derive = "2.4"
lazy_static = "1.4.0"
rand = "0.8.4"
serde_json = "1.0"